name: git-issue-release

on:
  pull_request:
    types: [closed]
  release:
    types: [published]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: git-issue-release
        uses: kouki-dan/git-issue-release@v0.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release-tag-pattern: ^v
          release-label: "release"
