name: git-issue-release

on:
  pull_request:
    types: [closed]
  release:
    types: [published]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: git-issue-release
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release-tag-prefix: v
          release-label: "release"
